#!/bin/sh

#rm Main.bin
rm Main.elf
rm Main.o
rm Main.map
#rm Main.srec
arm-linux-gnueabi-gcc -g -fno-common  -march=armv7-a -mlittle-endian -mtune=cortex-a7 -I../../Source/Module  -c Main.c
arm-linux-gnueabi-gcc -g -fno-common  -march=armv7-a -mlittle-endian -mtune=cortex-a7 -I../../Source/Module  -c vsnprintf.c
arm-linux-gnueabi-gcc -g -r -fno-common  -Wl,--build-id=none -Wl,-eEntryPoint -nostdlib -L/usr/lib/arm-none-eabi  -T Main.ld -Xlinker -Map=Main.map -o Main.elf Main.o vsnprintf.o -lgcc -lc
#arm-linux-gnueabi-objcopy --image-base 0x70000000 -O srec Main.elf Main.srec

